name: Send Bluesky Post

on:
    [repository_dispatch]

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download media if present
        uses: wei/wget@v1
        with:
          args: ${{ github.event.client_payload.media_link }}
      - name: Save file name from media_link as a variable
        id: media
        run: |
          echo "$(basename ${{ github.event.client_payload.media_link }})" >> $GITHUB_OUTPUT
      - name: Post to the bad jack crypto website
        uses: myConsciousness/bluesky-post@v3
        with:
          text: ${{ github.event.client_payload.text }}
          media: ${{ steps.media.outputs.output1 }}
          media-alt: ${{ github.event.client_payload.media_alt }}
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
          retry-count: 5
